import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Celso \"Data Analyst\" Fuentes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-2 md:grid-cols-4 text-lg gap-4 font-mono mt-4 flex-row justify-center border-4 border-solid border-blue-400"> 
          <div className="text-center ml-2 flex-row justify-center">
            <Link href={"/"}> Home </Link>
          </div>
          <div className="text-center flex-row justify-center">
            <Link  href={"/DC"}> Data Cleaning Projects</Link>
          </div>
          <div className="text-center ml-2 md:ml-0 flex-row justify-center">
            <Link href={"/EDA"}> EDA Projects</Link>
          </div>
          <div className="text-center ml-2 flex-row justify-center">
            <Link href={"/DA"}> Data Analysis Projects</Link> 
          </div>   
        </div>

        {children}
      </body>
    </html>
  );
}
